name: Build Release Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: Horus.Temrinal.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build
      
    - name: Publish
      run: dotnet publish src/Horus.Terminal/Horus.Terminal.csproj -c Release -p:DebugType=None
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Horus.Terminal
        path: src/Horus.Terminal/bin/Release/net6.0/publish
